feat/ Implemented LIC4 & unit test
Lussebullen/DD2480_DECIDE pull request #56
Opened 2024-01-29 13:31 UTC by empazi

Implemented LIC4 and its respective unit tests. 
Added exception handling to App.java to allow for LICS to throw exceptions

fixes #6

2024-01-30 13:33 UTC, Omar-AV commented
Conflict currently exists so review is on hold until resolved.

2024-01-30 15:49 UTC, emilsjol commented
When running tests on this branch locally, I get that 1 test is skipped. This doesn't seem to be the case for one other branch I tested (issue/3) or the main branch. To ensure this branch works I propose this should be fixed before merging

2024-01-31 15:26 UTC, emilsjol commented on decide/src/main/java/group17/App.java
What is the reasoning for rewriting App.java in this way so that evaluateLics throws exception? Previously the lics themselves threw exceptions,

2024-01-31 15:27 UTC, emilsjol commented on decide/src/main/java/group17/LicAnalyzer.java
The way exceptions are thrown here doesn't provide a lot of information when the exception occurs. Compare to other lics, where there is a line included.

2024-01-31 15:35 UTC, emilsjol commented on decide/src/main/java/group17/LicAnalyzer.java
> +            for(int j = i; j < input.Q_PTS + i; j++)
Potential index out of bounds if Q_PTS == NUMPOINTS and i > 0.

2024-01-31 15:37 UTC, emilsjol requested changes
I'm unsure about the decision regarding how to throw exceptions, but if it can be merged with no problems I'm fine with it. I think there is a potential index out of bounds exception in the nested for loop.

2024-01-31 16:04 UTC, empazi commented on decide/src/main/java/group17/App.java
When I added the try/catch block I just added throws on all related methods, but it is indeed unnecessary, I removed it now.

2024-02-01 08:55 UTC, emilsjol approved these changes
Thanks for takes notes into consideration. Good job!

2024-02-01 08:55 UTC, merged