feat/Implemented LIC14 and corresponding unit tests
Lussebullen/DD2480_DECIDE pull request #76
Opened 2024-01-31 14:59 UTC by empazi

Implemented LIC14 and unit tests for LIC14

Test check 2 cases of valid inputs, and 2 cases of invalid input

Closes #16

2024-01-31 15:20 UTC, Omar-AV commented
Currently exists a merge conflict hindering code review.

2024-02-01 20:19 UTC, Omar-AV requested changes
Review request to try syncing local improvements in App.java with latest change in origin/main.

2024-02-01 22:02 UTC, emilsjol approved these changes
Since there was a relevant update since Omar's comment, I consider it complete. Good job!

2024-02-01 22:03 UTC, Omar-AV approved these changes

2024-02-01 22:04 UTC, merged